[package]
name = "Igneous"
version = "0.1.0"
authors = ["BillK <bluesky42624@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = "0.8.5"
regex = "1"
rusqlite = "0.23.1"
strsim = "0.10.0"
